"""Frases de prueba para el agente grande (examples/hotel.json).

Ninguna aparece tal cual en las frases de entrenamiento: son paráfrasis, con faltas, sin tildes,
abreviaturas o de forma coloquial, como escribe la gente en un chat. Se escribieron en seis rondas
y con los fallos de cada una se añadieron frases al agente (tools/build_hotel.py), así que aquí
acierta casi todas. La medida honesta es la de la última ronda antes de usarla: con frases nunca
vistas acertó el 91,5 % (118 de 129) y rechazó el 82,6 % de las que no tenían que ver con el hotel.
"""

EN_DOMINIO = {
    "saludo": ["hola buenas tardes!", "buenass", "hola que tal, buenas", "buenos dias mira", "hey hola",
               "buenas noches, hay alguien?", "hola hola", "hola, buenos dias a todos", "eyy buenas", "buen dia"],
    "saludo.que_tal": ["como estas tu", "todo bien por ahi?", "que tal te va hoy", "que tal andas mira?",
                       "como va todo por ahi", "hola mira, que tal estas?", "cómo te va el día?"],
    "agradecimiento": ["muchas gracias por todo!!", "gracias, eres muy amable", "mil gracias de verdad",
                       "te lo agradezco mucho", "muchisimas gracias por la ayuda", "gracias, de verdad",
                       "gracias guapisima", "muchas gracias, muy util", "gracias por todo, muy amable",
                       "mil gracias por la ayuda", "genial, muchas gracias", "te debo una, gracias"],
    "despedida": ["adios, hasta otra", "bueno, me despido ya", "nada mas, adios", "vale, hasta luego entonces",
                  "adios, buenas noches y gracias", "bueno pues nada, adios", "hasta luego mira",
                  "me voy ya, hasta pronto", "nada más, hasta luego", "chao, buen día", "venga, hasta mañana",
                  "me piro, adiós"],
    "bot.identidad": ["eres una maquina?", "hablo con un humano o con un bot?", "como te llamabas?",
                      "quien te ha hecho", "usted es una persona?", "con quien estoy hablando",
                      "eres de verdad o un programa?", "como es tu nombre?", "tu eres un robot o una persona?",
                      "donde vives tú?", "eres una persona de carne y hueso?", "quién está al otro lado?"],
    "charla.personal": ["tienes pareja?", "que musica escuchas", "te gusta el mar?", "cual es tu comida favorita",
                        "que te gusta hacer a ti?", "tienes novio o novia?", "tienes algun hobby?",
                        "te gusta el flamenco?", "qué haces los fines de semana?"],
    "bot.ayuda": ["que cosas puedes hacer?", "en que me ayudas", "no se que hacer, ayudame", "que puedo preguntarte",
                  "para que me puedes servir", "dime que puedes hacer por mi", "necesito que me ayudes con una cosa",
                  "que me puedes contar del hotel?", "qué tipo de cosas sabes hacer?",
                  "qué preguntas te puedo hacer?", "para qué sirves exactamente?"],
    "charla.cumplido": ["eres muy apañada", "me encanta como me ayudas", "eres buenisima", "eres muy maja de verdad",
                        "que asistente mas buena", "que rapida contestas, me encanta", "me encanta hablar contigo",
                        "qué crack eres", "me has ayudado un montón, eres genial"],
    "charla.insulto": ["eres un bot inutil", "que tonta eres", "no vales para nada", "menuda porqueria de asistente",
                       "eres una inutil total", "vaya asistente mas malo", "eres una pesada",
                       "no sabes nada de nada", "menuda inutil estas hecha", "eres un desastre de bot",
                       "eres más tonta que una piedra", "vaya mierda de bot"],
    "charla.risa": ["jajajaj", "jejeje", "jajaja me parto"],
    "charla.chiste": ["cuentame otro chiste", "sabes chistes?", "hazme reir un poco", "un chiste porfa",
                      "cuentame uno gracioso", "cuentame un chistecito", "dime algo que me haga reir",
                      "cuéntame algo divertido"],
    "charla.esperar": ["espera un segundito", "dame un momento porfa", "un momento que miro una cosa",
                       "un momento por favor", "espera que pregunto a mi mujer", "un segundito que lo miro",
                       "espérame un momentito"],
    "charla.afirmacion": ["vale perfecto", "ok entendido", "de acuerdo, muy bien", "perfecto, así está bien"],
    "charla.negacion": ["no hace falta gracias", "no, de momento nada", "nada, no te preocupes", "nop"],
    "charla.no_entiendo": ["no te he entendido", "que dices?? no es eso", "me puedes repetir?",
                           "no entiendo nada de lo que dices", "eso no es lo que he preguntado", "cómo dices?",
                           "no entiendo lo que me dices", "eh? qué?"],
    "charla.hora": ["que hora es ahora", "sabes que dia es hoy?"],
    "reserva.habitacion": ["quiero reservar una habitacion doble para el sabado",
                           "teneis habitacion libre para mañana?",
                           "necesito una habitacion para 2 personas 3 noches", "me gustaria reservar una suite",
                           "hay disponibilidad para el puente de diciembre?",
                           "quiero hacer una reserva para 4 personas",
                           "reservar una individual para el lunes que viene",
                           "quiero una habitacion familiar para este finde", "busco habitacion para dos noches",
                           "quisiera reservar habitacion", "quisiera reserbar una abitacion para el viernes",
                           "me reserva usted una doble para dos noches?",
                           "tienen habitaciones disponibles para la semana que viene?",
                           "necesitamos una habitacion para 3 adultos", "quiero hacer una reserva de una noche",
                           "teneis libre una doble para el sabado que viene?",
                           "quiero reservar 2 noches para 4 personas",
                           "me gustaria quedarme en vuestro hotel en navidad",
                           "quisiera hacer una reserva para mañana", "hay habitaciones para este fin de semana?",
                           "necesito una habitacion individual para el martes",
                           "quiero reservar una habitacion para el 14 de febrero",
                           "buscamos habitacion doble 2 noches", "me podrias reservar una habitacion para el lunes?",
                           "somos tres, teneis habitacion para mañana?",
                           "reservar suite para nuestro aniversario el sabado",
                           "habria habitacion libre esta noche?",
                           "quisiera reservar habitación para el puente de diciembre",
                           "tenéis habitación libre para este finde?", "necesito alojamiento para dos noches",
                           "hay disponibilidad para el 20 de noviembre?",
                           "me gustaría una habitación para la semana que viene",
                           "quiero alojarme tres noches en noviembre", "busco habitación para dos adultos y un niño",
                           "tenéis algo libre para el 8 de diciembre?", "quiero coger una habitación"],
    "reserva.habitacion.fechas": ["quiero una doble del 10 al 13 de noviembre",
                                  "reservar desde el lunes hasta el miercoles",
                                  "teneis algo entre el 2 y el 4 de mayo?",
                                  "del 15 al 18 de agosto para dos personas",
                                  "llegamos el 4 de julio y nos vamos el 8", "del 5 al 8 de marzo para dos",
                                  "desde el sabado hasta el martes, habitacion doble",
                                  "habitacion del 7 al 9 de enero", "entre el 22 y el 25 de julio para dos personas",
                                  "del 1 al 4 de agosto para 4 personas", "desde el jueves al domingo",
                                  "habitación del 5 al 8 de enero",
                                  "busco hotel desde el 14 hasta el 17 de noviembre",
                                  "una doble desde el 2 hasta el 5 de noviembre",
                                  "del 20 al 23 de octubre para 3 personas"],
    "reserva.precios": ["cuanto cuesta la habitacion doble", "que precio tiene la noche", "cuanto vale la suite?",
                        "precio de una individual", "es muy cara la noche?", "cuanto cobrais por noche",
                        "cuanto sale una noche en la habitacion con vistas",
                        "cuanto me cuesta una noche en la suite?", "precio de la habitacion familiar por noche",
                        "cuanto valen las habitaciones?", "que precio tiene la habitacion doble con vistas",
                        "que vale la noche en temporada alta?", "cuanto cuesta la habitacion mas barata?",
                        "precio de una doble para el finde?", "a cuánto está la noche en la doble?",
                        "qué precio tiene dormir un sábado?"],
    "reserva.habitaciones": ["que habitaciones teneis", "como es la suite?",
                             "la habitacion familiar cuantas camas tiene", "las habitaciones tienen terraza?",
                             "diferencias entre la doble y la superior", "que diferencia hay entre las habitaciones",
                             "la suite tiene terraza?", "la habitacion doble es grande?",
                             "que tipos de habitacion hay?", "como son las habitaciones familiares?",
                             "las dobles tienen dos camas?", "qué tipos de habitación tenéis?",
                             "la familiar cuántas camas tiene?"],
    "reserva.consultar": ["no me ha llegado el correo de la reserva", "quiero ver mi reserva",
                          "mi reserva esta confirmada?", "como compruebo mi reserva",
                          "quiero comprobar si mi reserva esta bien hecha",
                          "no me ha llegado la confirmacion de la reserva",
                          "como puedo ver los datos de mi reserva?", "quiero revisar los datos de mi reserva",
                          "me podéis decir qué tengo reservado?",
                          "me podéis confirmar que tengo la reserva bien hecha?", "quiero ver cómo está mi reserva"],
    "reserva.modificar": ["quiero cambiar la fecha de mi reserva", "necesito modificar mi reserva",
                          "puedo cambiar las fechas de la reserva?", "quiero añadir otra noche a la reserva",
                          "necesito cambiar el dia de mi reserva", "puedo modificar la reserva que hice?",
                          "me equivoque de fecha al reservar, quiero cambiarla",
                          "quiero cambiar mi reserva a otro fin de semana",
                          "necesito cambiar la fecha de mi reserva", "quiero modificar una reserva que ya hice",
                          "tengo que cambiar las fechas de la reserva",
                          "me gustaría añadir una noche más a mi reserva"],
    "reserva.cancelar": ["quiero anular mi reserva", "cancelar reserva porfa", "como puedo cancelar la reserva?",
                         "tengo que cancelar, no puedo ir", "tengo que anular la reserva",
                         "quiero cancelar la reserva que hice", "cancelad mi reserva porfavor",
                         "no vamos a poder ir, cancelar la reserva", "anulad la reserva que tengo",
                         "queremos cancelar la reserva de la semana que viene", "quiero anular la reserva",
                         "ya no vamos a ir, cancelad la reserva por favor"],
    "reserva.politica_cancelacion": ["si cancelo me devolveis el dinero?", "hasta cuando se puede cancelar gratis",
                                     "que pasa si anulo la reserva", "la cancelacion tiene coste?",
                                     "se puede cancelar sin coste?", "cuanto me cobran si cancelo",
                                     "que condiciones tiene la cancelacion?", "me devuelven el dinero si anulo?",
                                     "cancelar tiene penalizacion?", "si cancelo me devuelven el dinero?",
                                     "hasta cuándo puedo cancelar gratis?",
                                     "si al final no puedo ir me cobráis algo?"],
    "reserva.pago": ["se puede pagar con tarjeta?", "aceptais bizum o efectivo", "cuando se paga la habitacion",
                     "hay que pagar por adelantado?", "como puedo pagar", "se puede pagar en efectivo en recepcion?",
                     "aceptan tarjeta de credito?", "puedo pagar al llegar?", "se puede pagar con bizum?",
                     "cuando me cobrais la estancia?", "puedo pagar con amex?", "se puede pagar en efectivo?",
                     "cuándo me cobráis la habitación?"],
    "reserva.ofertas": ["teneis descuentos?", "hay alguna promocion ahora?", "tengo un codigo de descuento",
                        "ofertas especiales", "tienen alguna oferta especial?",
                        "hay descuentos reservando en la web?", "hay alguna oferta para el spa?",
                        "tenis descuentos para estancias largas?", "tenéis algún descuento?",
                        "hay alguna promo ahora?", "hay algún chollo para este mes?",
                        "tenéis precio especial para estudiantes?"],
    "reserva.grupos": ["somos 25 personas, teneis precio de grupo?", "necesito 12 habitaciones para un grupo",
                       "reserva para grupo grande", "somos un grupo de 25 personas, hacéis precio?",
                       "reserva para una boda con muchos invitados", "vamos 30 personas de una asociación",
                       "necesitamos 12 habitaciones para un viaje de empresa"],
    "reserva.factura": ["me podeis mandar la factura?", "necesito la factura a nombre de la empresa",
                        "como consigo la factura de la estancia", "necesito una factura de mi estancia",
                        "me pueden enviar la factura?", "necesito la factura con los datos de mi empresa",
                        "necesito factura a nombre de mi empresa", "me podéis mandar la factura?",
                        "me hacéis factura con mi cif?", "necesito el justificante de pago"],
    "estancia.horarios": ["a que hora tengo que dejar la habitacion", "cuando es el check in",
                          "la recepcion abre toda la noche?", "a que hora se puede entrar a la habitacion?",
                          "hasta que hora tengo la habitacion?", "a que hora se hace el check out?",
                          "a partir de que hora puedo llegar?",
                          "a que hora hay que salir de la habitacion el ultimo dia?",
                          "hasta qué hora hay que dejar la habitación?",
                          "a partir de qué hora puedo coger la habitación?",
                          "a qué hora tengo que dejar libre la habitación?"],
    "estancia.checkin_anticipado": ["podemos entrar antes de las 15?",
                                    "llegamos a las 10 de la mañana, podemos entrar ya?",
                                    "se puede hacer el check in temprano?", "podria entrar a las 11 de la mañana?",
                                    "se puede entrar antes de hora?",
                                    "llegamos a las 9 de la mañana, podemos entrar antes?",
                                    "nuestro vuelo llega a las 8 de la mañana, podemos entrar pronto?",
                                    "es posible entrar a la habitación antes de las 3?"],
    "estancia.checkout_tardio": ["puedo dejar la habitacion mas tarde?", "podemos salir a las 2 de la tarde?",
                                 "cuanto cuesta quedarse hasta la tarde el ultimo dia",
                                 "se puede salir mas tarde de las 12?", "nos podemos quedar hasta las 3?",
                                 "podria quedarme en la habitacion hasta las 5?",
                                 "podría quedarme en la habitación hasta las 4?",
                                 "se puede salir más tarde el último día?",
                                 "nos podemos ir a las 3 de la tarde el último día?",
                                 "cuánto cuesta dejar la habitación más tarde?"],
    "estancia.documentacion": ["que documentacion hace falta?", "necesito el dni para entrar?",
                               "se puede hacer el check in online?", "qué necesito llevar para el check in?",
                               "hace falta el dni?", "tengo que llevar el pasaporte?",
                               "qué documentos piden al llegar?"],
    "estancia.equipaje": ["puedo dejar la maleta antes de entrar?", "teneis donde guardar maletas?",
                          "me guardais las maletas despues de salir", "donde puedo dejar las maletas?",
                          "guardan equipaje?", "donde dejo el equipaje antes de la hora de entrada?",
                          "puedo dejar las maletas después de dejar la habitación?",
                          "nos guardáis las maletas hasta la noche?", "dónde dejo el equipaje si llego pronto?"],
    "estancia.wifi": ["cual es la clave del wifi", "hay wifi gratis?", "como me conecto al wifi",
                      "teneis internet en la habitacion?", "hay wifi en el hotel?", "me das la contraseña del wifi?",
                      "el wifi funciona en la terraza?", "contraseña wifi porfa", "necesito la clave del wifi",
                      "hay internet gratis?", "cuál es la clave del wifi?", "cuál es la contraseña de la red?"],
    "estancia.parking": ["teneis aparcamiento?", "cuanto cuesta aparcar", "donde puedo dejar el coche",
                         "se puede reservar plaza de garaje?", "tienen garaje?", "cuanto cuesta el garaje por dia?",
                         "hay parking para coches?", "cuanto vale dejar el coche en el parking?",
                         "teneis parking para la autocaravana?", "tenéis garaje?",
                         "hay sitio para aparcar la furgoneta?", "cuánto cuesta el garaje por noche?"],
    "estancia.mascotas": ["puedo llevar a mi perrita?", "admitis mascotas?", "dejan llevar perro?",
                          "se aceptan gatos?", "puedo ir con mi perro pequeño?", "aceptan perros?",
                          "se pueden llevar perros grandes?", "viajo con mi gato, hay problema?",
                          "puedo traer a mi perro al hotel?", "puedo ir con mi gato?", "admitís perros grandes?",
                          "mi perrito puede dormir en la habitación?"],
    "estancia.ninos": ["teneis cuna para el bebe?", "hay club para niños?", "cuanto cuesta la cama supletoria",
                       "hay cunas disponibles?", "cuanto pagan los niños de 5 años?",
                       "hay actividades para los niños?", "tenis cuna para un bebe de 1 año?",
                       "mi hijo de 2 años paga?", "hay cama para niños?", "tenéis cunas para bebés?",
                       "hay actividades para críos?", "tenéis cama para niños?", "hay animación infantil?"],
    "estancia.accesibilidad": ["tengo movilidad reducida, hay habitaciones adaptadas?", "el hotel tiene ascensor?",
                               "es accesible en silla de ruedas", "el hotel tiene rampas?",
                               "hay habitacion adaptada para silla de ruedas?",
                               "voy en silla de ruedas, está adaptado el hotel?",
                               "tenéis habitaciones para minusválidos?",
                               "mi madre va en silla de ruedas, hay rampa?", "tenéis ascensor adaptado?"],
    "estancia.fumar": ["se puede fumar en la habitacion?", "donde se puede fumar", "hay zona para fumar?",
                       "se puede fumar en las habitaciones?", "hay zona de fumadores?"],
    "estancia.lavanderia": ["teneis lavanderia?", "me podeis lavar la ropa?", "hay servicio de planchado?",
                            "dónde puedo lavar ropa?", "me podéis lavar unas camisas?",
                            "hay lavadora para los clientes?"],
    "estancia.equipamiento": ["la habitacion tiene secador?", "hay caja fuerte en la habitacion?",
                              "hay aire acondicionado en las habitaciones?", "las habitaciones tienen minibar?",
                              "la habitacion tiene secador de pelo?", "hay plancha en las habitaciones?",
                              "hay aire en la habitacion?", "la habitacion tiene caja de seguridad?",
                              "las habitaciones tienen aire acondicionado?", "las habitaciones tienen tele?"],
    "restaurante.desayuno": ["a que hora se desayuna?", "esta incluido el desayuno?", "cuanto vale el desayuno",
                             "el desayuno tiene cosas sin gluten?", "a que hora empieza el desayuno?",
                             "el desayuno esta incluido en el precio?", "que se desayuna en el hotel?",
                             "hasta que hora sirven el desayuno?", "el desayuno a que hora empieza?",
                             "cuanto cuesta desayunar en el hotel?"],
    "restaurante.info": ["teneis restaurante en el hotel?", "a que hora se puede cenar?",
                         "que se come en el restaurante", "hay menu vegetariano?",
                         "que tal se come en el restaurante?", "el restaurante abre a mediodia?",
                         "el restaurante tiene comida vegana?", "a que hora se puede comer en el restaurante?",
                         "que tal es el restaurante del hotel?", "a que hora se cena en el restaurante?",
                         "qué tal se come en el restaurante?", "tenéis menú vegano?",
                         "a qué hora abre el restaurante para cenar?", "tenéis opciones sin gluten?"],
    "restaurante.reservar": ["quiero reservar mesa para cenar esta noche", "mesa para 3 mañana a las 2",
                             "reserva para cenar el viernes a las 9 para dos", "me reservas mesa en el restaurante?",
                             "quiero reservar mesa para 4 el sabado a las 9 de la noche",
                             "reservame mesa para comer mañana", "reserva una mesa para cenar a las 21:30 para 2",
                             "queremos mesa para comer el domingo",
                             "reservad mesa para 6 el sabado a las 10 de la noche", "quiero mesa para comer hoy",
                             "quiero reservar mesa para cenar mañana", "mesa para 4 el sábado a las 2",
                             "resérvame mesa para dos esta noche", "quiero una mesa para cenar el viernes a las 9"],
    "restaurante.bar": ["hay algun bar en el hotel?", "a que hora abre la azotea", "donde puedo tomar una copa",
                        "hay terraza para tomar algo?", "dónde puedo tomar una copa?", "tenéis cócteles?",
                        "hay bar en la azotea?"],
    "restaurante.habitacion": ["hay room service?", "puedo pedir la cena a la habitacion?",
                               "me pueden subir comida a la habitacion?", "tenéis room service?",
                               "me podéis subir la cena a la habitación?", "se puede pedir comida a la habitación?",
                               "servicio de habitaciones hasta qué hora?"],
    "spa.info": ["cuanto cuesta el spa?", "que masajes teneis?", "teneis spa en el hotel",
                 "el spa que horario tiene?", "cuanto vale un masaje?", "el circuito spa cuanto cuesta?",
                 "que horario tiene el spa?", "que precio tienen los masajes?",
                 "el spa esta incluido en la habitacion?", "qué tiene el spa?", "cuánto cuesta entrar al spa?",
                 "qué tratamientos tiene el spa?", "el spa está incluido en el precio?"],
    "spa.reservar": ["quiero reservar un masaje para mañana", "reservame el circuito para dos el domingo",
                     "quiero cita para un masaje relajante", "reservar masaje en pareja",
                     "quiero reservar un masaje para el sabado por la tarde", "me reservas el spa para mañana?",
                     "reservame un masaje relajante para el viernes a las 5", "quiero cita en el spa para el sabado",
                     "quiero reservar el circuito spa para el domingo a las 12", "quiero pedir cita para un masaje",
                     "reservadme un facial para el viernes por la tarde",
                     "quiero reservar un masaje para dos mañana por la tarde",
                     "me apuntas al circuito termal el sábado?"],
    "piscina.info": ["hay toallas para la piscina?", "la piscina abre en invierno?", "hay piscina climatizada?",
                     "la piscina abre por la mañana?", "hasta que hora abre la piscina?",
                     "hasta qué hora abre la piscina?", "se puede usar la piscina en invierno?",
                     "la piscina tiene socorrista?"],
    "gimnasio.info": ["teneis gym?", "hay gimnasio en el hotel?", "teneis sala de fitness?", "tenéis gym?"],
    "habitacion.peticion": ["me podeis subir dos toallas a la 305?", "necesito otra almohada",
                            "me traeis una manta porfa", "falta papel higienico en el baño", "quiero un secador",
                            "me hace falta una almohada mas", "podeis subirme toallas a la 210?",
                            "podrian subir una manta a la 412?", "necesito mas toallas por favor",
                            "me suben una almohada a la habitacion 120?", "necesito una toalla mas",
                            "me hace falta otra manta", "podéis subirme más papel higiénico?",
                            "me traéis otra almohada?", "nos faltan toallas en la 214"],
    "habitacion.limpieza": ["a que hora pasan a limpiar?", "no me han limpiado la habitacion",
                            "quiero que limpien mi habitacion", "pueden limpiar la habitación?",
                            "no han hecho la cama hoy", "podéis pasar a limpiar ahora?",
                            "no han cambiado las toallas"],
    "habitacion.averia": ["no funciona el aire", "la tele no se enciende", "no hay agua caliente en la ducha",
                          "se ha roto la cisterna", "la luz del baño no va", "el aire acondicionado no enfria",
                          "no funciona la luz de la habitacion", "la ducha no tiene agua caliente en la 210",
                          "no funciona la tele de mi habitacion", "no va la luz en la habitacion 305",
                          "se ha fundido una bombilla", "el aire no enfría", "no funciona el agua caliente",
                          "la puerta del baño no cierra", "la televisión no se ve"],
    "habitacion.cambio": ["quiero cambiar de habitacion", "no me gusta mi habitacion, quiero otra",
                          "quiero que me cambien de habitacion", "esta habitacion no me gusta",
                          "podemos cambiar de habitacion?", "quiero que me cambien de habitación",
                          "la habitación da a un patio, podéis darme otra?",
                          "me podéis cambiar a una habitación más grande?",
                          "huele a humedad, quiero otra habitación"],
    "queja.ruido": ["hay un ruido horrible", "no puedo dormir con tanto ruido", "los de al lado no paran de gritar",
                    "hay mucho jaleo en el pasillo", "no me dejan dormir los de al lado",
                    "hay muchisimo ruido y no puedo dormir", "los vecinos estan haciendo una fiesta",
                    "hay ruido toda la noche y no hay quien duerma", "los de al lado no paran de hacer ruido",
                    "no he pegado ojo por el ruido", "los del piso de arriba hacen mucho ruido"],
    "queja.general": ["quiero poner una reclamacion", "estoy muy disgustado con el servicio", "esto es inaceptable",
                      "quiero reclamar", "el trato ha sido muy malo", "quiero hacer una queja formal",
                      "estoy muy enfadada con el hotel", "el servicio ha sido muy malo, quiero reclamar",
                      "estoy muy descontento con el servicio", "quiero poner una reclamación",
                      "estoy muy enfadado con el hotel"],
    "objetos.perdidos": ["me he olvidado el cargador en la habitacion", "perdi unas gafas en el hotel",
                         "creo que me deje la chaqueta", "me he dejado algo en la habitacion",
                         "he perdido el movil en el hotel", "me deje el cargador del movil en el hotel",
                         "perdí unas gafas en el hotel", "me he olvidado una chaqueta en el hotel",
                         "habéis encontrado un reloj?"],
    "servicio.despertador": ["me podeis despertar a las 7?", "quiero que me despierten mañana a las 8",
                             "despertador a las 6 y media porfa", "me despiertan a las 6?",
                             "quiero una llamada de despertador a las 8", "me pueden despertar a las 6 y media?",
                             "llamada para despertarme a las 8", "necesito que me despierten a las 5 y media",
                             "me podéis llamar a las 6 para despertarme?", "me podéis despertar a las 7 y media?",
                             "necesito que me llaméis mañana a las 6 para despertarme"],
    "servicio.taxi": ["me pedis un taxi porfa", "necesito un taxi ya", "llamadme un taxi para las 9",
                      "me podeis pedir un taxi?", "necesito un taxi para ir al centro", "pidame un taxi por favor",
                      "necesito un taxi para las 8 de la mañana", "pedidme un taxi para dentro de media hora",
                      "me pides un taxi?", "llámame un taxi por favor", "necesito un taxi para las 10"],
    "servicio.traslado": ["quiero reservar el traslado al aeropuerto",
                          "me podeis recoger en el aeropuerto el lunes?", "reservame un transfer al aeropuerto",
                          "quiero que me recojan en el aeropuerto el viernes",
                          "reservar el traslado al aeropuerto para mañana",
                          "quiero un transfer al aeropuerto el lunes a las 7",
                          "nos recogeis en el aeropuerto el sabado?",
                          "reservame el traslado desde el aeropuerto para el jueves a las 4 de la tarde",
                          "quiero que me recojan en el aeropuerto el sábado",
                          "necesito transporte al aeropuerto mañana a las 5",
                          "necesito que me llevéis al aeropuerto el martes a las 7",
                          "quiero reservar el traslado desde el aeropuerto para el viernes"],
    "servicio.traslado.info": ["cuanto cuesta el traslado al aeropuerto?", "como llego del aeropuerto al hotel",
                               "teneis transfer desde el aeropuerto?", "cuanto se tarda del aeropuerto al hotel?",
                               "tenéis servicio de traslado al aeropuerto?",
                               "cuánto cuesta el transfer del aeropuerto?", "tenéis lanzadera al aeropuerto?",
                               "cuánto se tarda en llegar al aeropuerto?"],
    "info.servicios": ["que servicios tiene el hotel?", "que instalaciones teneis", "qué servicios tiene el hotel?",
                       "qué cosas tiene el hotel?", "qué servicios ofrecéis?"],
    "info.ubicacion": ["cual es la direccion del hotel", "estais cerca del centro?", "como llego en coche al hotel?",
                       "en que direccion estais?", "donde esta exactamente el hotel?",
                       "esta lejos el hotel de la playa?", "como se va al hotel desde la estacion?",
                       "cuál es la dirección del hotel?", "dónde estáis exactamente?",
                       "cómo llego desde la estación de tren?", "en qué zona está el hotel?",
                       "me pasas la ubicación?"],
    "info.contacto": ["cual es el telefono del hotel", "a que correo os escribo?", "me das el telefono del hotel?",
                      "cual es el email de reservas?", "me das un telefono de contacto?",
                      "tenéis email de contacto?", "tenéis un número de teléfono?"],
    "contacto.humano": ["quiero hablar con alguien de recepcion", "pasame con una persona porfa",
                        "necesito hablar con un humano", "quiero hablar con recepcion", "me pasas con alguien?",
                        "quiero hablar con una persona de verdad", "me puede atender alguien?",
                        "quiero que me atienda una persona", "quiero hablar con alguien de recepción",
                        "pásame con una persona real"],
    "contacto.llamada": ["me podeis llamar por telefono?", "llamadme al 655443322", "quiero que me llameis",
                         "me podéis llamar por teléfono?", "podéis llamarme al móvil?",
                         "que me llame alguien por favor"],
    "opinion.positiva": ["nos ha encantado el hotel", "todo perfecto, muy contentos", "el hotel es una maravilla",
                         "el hotel nos ha encantado", "que bien lo hemos pasado", "nos ha encantado la estancia",
                         "todo perfecto, repetiremos", "el personal es encantador"],
    "info.transporte": ["como me muevo por la ciudad?", "hay bus al centro?", "puedo alquilar una bici?",
                        "cómo puedo moverme por la ciudad?", "dónde se coge el autobús al centro?"],
    "info.turismo": ["que me recomiendas ver en malaga", "que sitios visitar", "que hago esta tarde?",
                     "merece la pena el museo picasso?", "que puedo visitar por la zona?",
                     "que hay para ver en malaga?", "que monumentos hay cerca?", "que me recomiendas ver hoy?",
                     "que se puede hacer en malaga?", "qué se puede visitar en málaga?",
                     "qué me recomiendas ver en la ciudad?", "hay algún concierto esta semana?",
                     "qué planes hay en málaga este finde?", "qué visitar en málaga en dos días?",
                     "merece la pena ver el castillo?"],
    "info.playas": ["donde esta la playa mas cerca", "que playa me recomiendas", "la playa esta cerca?",
                    "la playa queda cerca?", "que playas hay por aqui?", "hay alguna playa cerca del hotel?",
                    "la playa está lejos?", "qué playa hay cerca?", "cuál es la mejor playa?"],
    "info.restaurantes_cerca": ["donde se come bien por aqui?", "recomiendame un sitio de tapas",
                                "donde puedo cenar cerca del hotel?", "algun sitio bueno para cenar cerca?",
                                "donde puedo tomar tapas?", "donde se puede comer pescado cerca?",
                                "algun bar de tapas por la zona?", "algun restaurante para comer espetos?",
                                "algún sitio para comer pescaito por la zona?",
                                "me recomiendas un restaurante cerca?", "algún bar de tapas cerca?"],
    "info.excursiones": ["que excursiones me recomiendas?", "como voy al caminito del rey", "excursion a nerja",
                         "podemos ir a ronda en el dia?", "hay excursiones a granada?",
                         "se puede ir a nerja desde aqui?", "se puede ir a Ronda en el día?",
                         "qué excursiones se pueden hacer desde málaga?"],
    "info.tiempo": ["que tiempo hace hoy?", "va a llover mañana?", "hace frio en malaga?",
                    "que tal tiempo hace en malaga?", "va a hacer calor esta semana?", "hara sol mañana?",
                    "va a llover este fin de semana?", "hace sol hoy?", "qué temperatura hace?"],
    "info.eventos": ["teneis salas para reuniones?", "quiero hacer un evento de empresa",
                     "haceis celebraciones de bodas?", "podemos celebrar un cumpleaños en el hotel?",
                     "alquiláis salas para reuniones?"],
    "info.bonos_regalo": ["teneis tarjetas regalo?", "quiero regalar una noche", "tenéis cheques regalo?",
                          "quiero regalar una estancia a mis padres"],
    "info.empleo": ["estais buscando personal?", "donde mando el curriculum", "quiero trabajar con vosotros",
                    "quiero mandar mi curriculum", "estáis buscando camareros?", "dónde mando mi cv?",
                    "hay trabajo de recepcionista?", "busco empleo, contratáis?"],
    "info.cerca": ["hay farmacia cerca?", "hay supermercado cerca del hotel?", "hay algún súper cerca?",
                   "hay alguna farmacia abierta cerca?", "dónde puedo sacar dinero?"],
    "info.urgencias": ["necesito un medico urgente", "me encuentro muy mal", "es una emergencia",
                       "me he cortado y sangra mucho", "necesitamos un medico", "necesito ir al hospital",
                       "me he hecho daño en el pie", "necesito un medico, me encuentro fatal",
                       "me encuentro fatal, necesito un médico", "dónde está el hospital más cercano?",
                       "me he caído y me duele mucho"],
}

# Frases que dependen de un contexto activo: (contextos, frase, intención esperada)
CON_CONTEXTO = [
    (["reserva", "reserva-confirmar"], "si, perfecto", "reserva.confirmar.si"),
    (["reserva", "reserva-confirmar"], "vale, confirmala", "reserva.confirmar.si"),
    (["reserva", "reserva-confirmar"], "no, aun no", "reserva.confirmar.no"),
    (["reserva", "reserva-confirmar"], "mejor para 3 personas", "reserva.cambiar.personas"),
    (["reserva", "reserva-confirmar"], "mejor la suite", "reserva.cambiar.habitacion"),
    (["reserva", "reserva-confirmar"], "que sean 4 noches", "reserva.cambiar.noches"),
    (["reserva", "reserva-confirmar"], "mejor el viernes que viene", "reserva.cambiar.fecha"),
    (["reserva", "reserva-confirmar"], "quiero cambiar una cosa", "reserva.cambiar"),
    (["cancelacion"], "si, anulala", "reserva.cancelar.si"),
    (["cancelacion"], "no no, no la anules", "reserva.cancelar.no"),
]

# Frases fuera de tema: deberían acabar en la intención de fallback
FUERA_DE_DOMINIO = [
    "cual es la capital de italia", "quien gano el mundial del 86", "cuanto es 15 por 3", "pon reggaeton",
    "llama a mi hermano", "quiero pedir sushi a domicilio", "mi lavadora pierde agua", "como se hace un gazpacho",
    "recomiendame una serie", "quien invento la bombilla", "cuantos km hay de la tierra a la luna",
    "traduce gracias al frances", "hazme un resumen del libro", "quiero comprar unas zapatillas",
    "cuanto vale un ordenador", "como abro una cuenta en el banco", "mi telefono no tiene cobertura en casa",
    "necesito un electricista", "como adelgazar 5 kilos", "que es un agujero negro",
    "quien es el mejor jugador de futbol", "a quien voto en las elecciones", "sacame un billete de avion a berlin",
    "busco un piso en alquiler", "zxcvbn", "ghjklñ", "pppppp", "mi gato no come", "me gustan los macarrones",
    "el coche de mi padre es rojo", "tengo que hacer la compra", "manda un correo a mi jefe",
    "apaga la calefaccion de mi casa", "cuantos años tiene el papa", "donde nacio cervantes",
    "como se llama la capital de japon", "reserva una pista de tenis en mi club", "quiero entradas para el futbol",
    "pide cita en la peluqueria", "cambiar el aceite del coche", "quien es messi", "como se hace una paella",
    "pon la tele del salon", "cuanto dinero tengo en el banco", "quiero un perro", "como se escribe hipopotamo",
    "recomiendame un libro", "que dia nacio picasso", "cuanto mide el everest", "cual es la mejor pizza del mundo",
    "necesito un taxi en madrid", "reservame un hotel en barcelona", "quiero cambiar mi tarifa de movil",
    "tengo frio en casa", "como arreglo una rueda pinchada", "me he quedado sin bateria",
    "quien es el presidente de francia", "como se dice perro en aleman", "recomiendame un disco",
    "cuanto cuesta un coche nuevo", "quiero aprender ingles", "como hago un pastel de chocolate",
    "que es la inflacion", "pon una cancion triste", "mi vecino tiene un perro", "me gusta mucho el cine",
    "cual es el planeta mas grande", "necesito un fontanero urgente", "como reinicio el portatil",
    "quiero comprar entradas para el teatro", "quien gano la champions", "cuanto es la raiz de 81",
    "como se cocina el arroz", "dime la capital de peru", "recomiendame un movil", "que significa ubicuo",
    "pon musica relajante", "quiero un gato", "como cambio una bombilla en mi casa", "mi coche hace un ruido raro",
    "cuando es el black friday", "quiero comprar un sofa", "dame un consejo para el amor",
    "como se juega al ajedrez", "cual es el animal mas rapido", "quien es taylor swift",
    "tengo que renovar el carnet de conducir", "como hago la declaracion de la renta",
    "recomiéndame una serie de netflix", "cuánto es 15 por 23?", "mi novia me ha dejado",
    "cómo cambio la rueda del coche?", "qué opinas de la política?", "cuál es el mejor móvil del mercado?",
    "traduce hola al chino", "cómo se llama el presidente de francia?",
    "tengo que hacer la declaración de la renta", "quiero comprar un coche", "escribe un poema",
    "cuánto pesa un elefante?", "mi ordenador va lento", "cuántos habitantes tiene china?",
    "quiero aprender a programar", "dónde puedo comprar bitcoins?", "hazme los deberes",
    "cuál es la raíz cuadrada de 2?", "quién pintó el guernica?", "cómo se hace el salmorejo?",
    "recomiéndame un podcast", "qué tal juega el betis?", "quiero cambiar de banco",
    "explícame qué es un agujero de gusano", "cómo se programa en python?", "dime un refrán",
    "quién es el rey de inglaterra?", "cuántos litros tiene una piscina olímpica?", "qué es el bitcoin?",
    "pon un vídeo de gatos", "cuál es la montaña más alta de españa?", "tengo que llevar el coche a la itv",
    "mi impresora no imprime", "quién ganó el tour de francia?", "cómo hago una transferencia?",
    "hazme una lista de la compra", "cuánto es 3 elevado a 4?", "qué significa la palabra efímero?",
    "recomiéndame una app de idiomas", "cómo se planta un tomate?",
]

# Conversaciones completas: (frases del usuario, intención y parámetros esperados al final)
DIALOGOS = [
    {
        "turnos": ["quiero reservar una habitacion doble", "el 12 de octubre", "3", "2"],
        "intencion": "reserva.habitacion",
        "parametros": {"habitacion": "doble", "noches": 3, "huespedes": 2},
    },
    {
        "turnos": ["una suite del 3 al 6 de diciembre para 2 personas"],
        "intencion": "reserva.habitacion.fechas",
        "parametros": {"habitacion": "suite", "huespedes": 2, "fecha_entrada": "2026-12-03",
                       "fecha_salida": "2026-12-06"},
    },
]
